# Generated by Django 5.1.1 on 2024-09-21 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stauts',
            new_name='status',
        ),
    ]
